# Multi-task training config
defaults:
  - _self_
  - data_module/data_split: discrete_gestures_split
  - lightning_module: multitask_module

data_location: D:/emg/emg_nature/emg_data
joint_data_location: D:/emg/emg2pose1/emg2pose-main/emg2pose-main/emg2pose_dataset/emg2pose_data
task: discrete_gestures

seed: 0
train: True
eval: True
num_nodes: 1

trainer:
  max_epochs: 250
  accelerator: gpu
  devices: 1

monitor_metric: val_accuracy
monitor_mode: max

callbacks:
  - _target_: pytorch_lightning.callbacks.LearningRateMonitor
  - _target_: pytorch_lightning.callbacks.ModelCheckpoint
    monitor: ${monitor_metric}
    mode: ${monitor_mode}
    save_last: True
    verbose: True

pretrained_encoder_ckpt: null

hydra:
  run:
    dir: logs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ${hydra.run.dir}
    subdir: ${hydra.job.num}_${hydra.job.override_dirname}/seed=${seed}
  output_subdir: hydra_configs
  job:
    name: method4-multitask
    config:
      override_dirname:
        exclude_keys:
          - seed
